spring:
  datasource:
    username: ${DB_USERNAME:localdb}
    url: ${DB_URL:jdbc:mysql://localhost:3306}
    password: ${DB_PASSWORD:localdb}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  mvc:
    hiddenmethod:
      filter:
        enabled: true
